runtime: python27

api_version: 1
threadsafe: true

env_variables:
  PUBSUB_TOPIC: news
  PUBSUB_VERIFICATION_TOKEN: 1234abc

# [START handlers]
handlers:
- url: /.*
  script: application.app
# [END handlers]

# [START libraries]
libraries:
- name: flask
  version: latest
- name: setuptools
  version: "36.6.0"
- name: grpcio
  version: latest
# [END libraries]