runtime: python37
api_version: 1
threadsafe: true

# [START handlers]
handlers:

- url: /.*
  script: CourseDelivery.app
# [END handlers]

# [START libraries]
libraries:
# [END libraries]

runtime_config:
  python_version: 3