runtime: python
env: flex
entrypoint: gunicorn  -b :$PORT main:app --timeout 1000


env_variables:
    PUBSUB_TOPIC: tweet
    # This token is used to verify that requests originate from your
    # application. It can be any sufficiently random string.
    PUBSUB_VERIFICATION_TOKEN: 1234abc
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

beta_settings:
  cloud_sql_instances: cloudcoursedelivery:australia-southeast1:universities

runtime_config:
  python_version: 3
# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
# [END handlers]

# pub/sub


## [START libraries]
#libraries:
#- name: flask
#  version: latest
#- name: ssl
#  version: latest
## [END libraries]