runtime: python27

api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /.*
  script: application.app
# [END handlers]

# [START libraries]
libraries:
- name: flask
  version: latest
- name: ssl
  version: latest
# [END libraries]

